# Generated by Django 5.0.6 on 2024-08-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_remove_reserva_viaje_reserva_destino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
