# Generated by Django 5.0.6 on 2024-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_delete_viaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_selec',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tarjeta',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reserva',
            name='apellidos',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(max_length=12, verbose_name='Usuario '),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='personas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
